config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts, controllers: {registrations: 'registrations'}
  root 'accounts#index'
  resources :accounts do
  	put 'doc', action: 'change_document', on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :posts
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  has_attached_file :document
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	paginates_per 15
  belongs_to :account
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	before_action :authenticate_account!
  def index
  	
  end

  def show
  	@account = Account.find params[:id]
  	@posts = @account.posts.page params[:page]
  end

  def edit
  	@account = Account.find params[:id]
  end

  def update
  	@account = Account.find params[:id]
  	if @account.update account_params
  		redirect_to @account
  	else
  		render 'edit'
  	end
  end

  def change_document
  	update
  end

  private
  def account_params
  	params.require(:account).permit(:document,:nickname,:first_name,:last_name,:email,:avatar)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
	  current_account
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	private

  def sign_up_params
    params.require(:account).permit(:avatar, :nickname, :first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:account).permit(:nickname, :first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/edit.html.erb
<%= form_for @account, html: { multipart: true } do |f| %>
	<p>
		<%= f.label :nickname %>
		<%= f.text_field :nickname %>
	</p>
	<p>
		<%= f.label :first_name %>
		<%= f.text_field :first_name %>
	</p>
	<p>
		<%= f.label :last_name %>
		<%= f.text_field :last_name %>
	</p>
	<p>
		<%= f.label :email %>
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :avatar %>
		<%= f.file_field :avatar, as: :file %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/accounts/index.html.erb
<h1>Accounts#index</h1>
<p>Find me in app/views/accounts/index.html.erb</p>

app/views/accounts/show.html.erb
<h1>Profile</h1>
<%= image_tag @account.avatar.url(:thumb) %>
<ul class="inline">
	<li><%= link_to "Edit", edit_account_path(@account) %></li>
</ul>
<ul>
	<li><strong>Nickname:</strong> <%= @account.nickname %></li>
	<li><strong>First name:</strong> <%= @account.first_name %></li>
	<li><strong>Last name:</strong> <%= @account.last_name %></li>
	<li><strong>Email:</strong> <%= @account.email %></li>
</ul>
<%= @account.document.url %>
<%= form_for :account, url: doc_account_url(@account), method: :put, html: {multipart: true} do |f| %>
	<p>
		<%= f.label :document %>
		<%= f.file_field :document %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>
<h3>Your posts</h3>
<% @posts.each do |post| %>
<p><%= post.title %></p>
<% end %>
<%= paginate @posts %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practise</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% if account_signed_in? %>
		<%= link_to current_account.nickname, current_account %> <%= link_to "Sign Out", destroy_account_session_path, method: :delete %>
  	<% else %>
		<%= link_to "Sign In", new_account_session_path %>
  	<% end %>
    <%= yield %>
  </body>
</html>